### ISSUE TITLE
Application crashes on startup. Missing settings file

### ISSUE THREAD

**Issue by fabianmoronzirfas** [kkitay/raccoon#2]
![racoon-error](https://user-images.githubusercontent.com/315106/48333111-894e8300-e656-11e8-81bb-a249e3ebc1fc.png)

**Comment by kkitay** [comment]
Thanks Fabian, working on fixing this now!

**Comment by kkitay** [comment]
Can you tell me what version of Mac OS you're using?

**Comment by fabianmoronzirfas** [comment]
I'm on MacOS 10.14

**Comment by kkitay** [comment]
Thanks! This is resolved with the new release o^_^o https://github.com/kkitay/raccoon/releases/tag/v1.0.1
